import type { SceneDef } from './AudioSyncedComposition'
import type { SubtitleEntry } from './scenes/SubtitleOverlay'

export interface CompositionDef {
  id: string
  props: {
    audioFile: string
    introVideo: string
    outroVideo: string
    introSec: number
    outroStartSec: number
    totalSec: number
    scenes: SceneDef[]
    subtitles: SubtitleEntry[]
  }
}

// AUTO-GENERATED from Whisper SRT — subtitles = actual speech
export const compositions: CompositionDef[] = [
  // ─── Process001 ───
  {
    id: 'Process001',
    props: {
      audioFile: 'p001-audio.m4a',
      introVideo: 'p001-intro.mp4',
      outroVideo: 'p001-outro.mp4',
      introSec: 3,
      outroStartSec: 48,
      totalSec: 51,
      scenes: [
        { type: 'layers' as const, startSec: 3.0, endSec: 8.5 },
        { type: 'layers' as const, startSec: 8.5, endSec: 13.2 },
        { type: 'text' as const, startSec: 13.2, endSec: 17.8 },
        { type: 'text' as const, startSec: 17.8, endSec: 21.5 },
        { type: 'layers' as const, startSec: 21.5, endSec: 28.5 },
        { type: 'layers' as const, startSec: 28.5, endSec: 35.5 },
        { type: 'stats' as const, startSec: 35.5, endSec: 38.5 },
        { type: 'ontologyGrid' as const, startSec: 38.5, endSec: 44.8 },
        { type: 'ontologyGrid' as const, startSec: 44.8, endSec: 51.0 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 3.0, text: '이거를 좀 차근차근 설명 드려볼게요.' },
        { startSec: 3.0, endSec: 8.5, text: '첫 번째로 이제 CEO 스태프는 5개의 레이어를 통해서 업무를 수행하게 되는데요.' },
        { startSec: 8.5, endSec: 13.2, text: '첫 번째로는 어떤 규칙에 의해서 움직이게 되고 그것들을' },
        { startSec: 13.2, endSec: 17.8, text: '규칙에 의해서 에이전트들, 각각의 AI 에이전트들이 움직이게 됩니다.' },
        { startSec: 17.8, endSec: 21.5, text: '그리고 이 에이전트들이 참고하는 지식들이 있어요.' },
        { startSec: 21.5, endSec: 28.5, text: '스킬들. 스킬들을 도메인, 업무 도메인별로 예를 들어서 재무, 디자인, 컨텐츠, 마케팅,' },
        { startSec: 28.5, endSec: 35.5, text: '프로덕트, 개발 이런 도메인별로 읽을 만한 자료들을, 스킬들을 플러그인으로 묶어 놨거든요.' },
        { startSec: 35.5, endSec: 38.5, text: '그래서 이 플러그인들을 읽는 작업이 있고요.' },
        { startSec: 38.5, endSec: 44.8, text: '네 번째로는 온톨로지라고 해서 이 기업의 여러 가지 역사와 자료와' },
        { startSec: 44.8, endSec: 51.0, text: '이런 것들이 전부 다 지식화되어 있는 날리지 베이스라고 하는 문서들이 있습니다.' },
      ],
    },
  },
  // ─── Hook001 ───
  {
    id: 'Hook001',
    props: {
      audioFile: 'h001-audio.m4a',
      introVideo: 'h001-intro.mp4',
      outroVideo: 'h001-outro.mp4',
      introSec: 4,
      outroStartSec: 55,
      totalSec: 58,
      scenes: [
        { type: 'comparison' as const, startSec: 9.0, endSec: 9.7 },
        { type: 'ontologyGrid' as const, startSec: 9.7, endSec: 15.3 },
        { type: 'text' as const, startSec: 15.3, endSec: 21.0 },
        { type: 'text' as const, startSec: 21.0, endSec: 26.1 },
        { type: 'ontologyGrid' as const, startSec: 26.1, endSec: 31.3 },
        { type: 'ontologyGrid' as const, startSec: 31.3, endSec: 39.3 },
        { type: 'comparison' as const, startSec: 39.3, endSec: 45.0 },
        { type: 'text' as const, startSec: 45.0, endSec: 49.6 },
        { type: 'ontologyGrid' as const, startSec: 49.6, endSec: 54.3 },
        { type: 'ontologyGrid' as const, startSec: 54.3, endSec: 58.0 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 0.3, text: '그래서 이렇게 온톨로지를 구축하는 일부터 했습니다.' },
        { startSec: 0.5, endSec: 9.0, text: '이걸 하면은 쉽게 말하면 진짜 AI가 우리 회사에서 제일 장기 근속한 사람처럼 여러 가지 속속들이 알게 되는 효과가 있어요.' },
        { startSec: 9.0, endSec: 9.7, text: '근데 걔네랑 에이전트 팀의 차이가 뭐냐고 한다면 우리 회사의 맥락을 알고 있냐 아니냐 이 차이거든요.' },
        { startSec: 9.7, endSec: 15.3, text: '그런 의미에서 온톨로지는 우리 회사의 맥락을 신입사원 온보딩 교육하듯이 역사가 어떻게 되고' },
        { startSec: 15.3, endSec: 21.0, text: '연역이 어떻게 되고 매출 규모가 어떻게 되고 주요 제품이 뭐며 주요 기능이 뭐며' },
        { startSec: 21.0, endSec: 26.1, text: '이런 개요, 팀, 제품, 기술, 시장, 투자 상황, 로드맵,' },
        { startSec: 26.1, endSec: 31.3, text: '고객 이런 것들의 정보를 잘 정리해 놓은 게 온톨로지예요.' },
        { startSec: 31.3, endSec: 39.3, text: '이 온톨로지라는 것들이 원래는 되게 구축하기가 많이 어렵고 수작업도 굉장히 많이 들어가고 다양한 데이터가 필요했는데' },
        { startSec: 39.3, endSec: 45.0, text: 'AI를 활용하면 온톨로지 구축이 좀 간단한 거의 경우에는 비교적 쉽게 됩니다.' },
        { startSec: 45.0, endSec: 49.6, text: '비교적 쉽게 되고 예전처럼 아주 고급 기술이 아니라 지금은' },
        { startSec: 49.6, endSec: 54.3, text: '마크다운 기반으로 온톨로지로 사용할 만한 것들을 지식체계를 잘 정리해 놓으면' },
        { startSec: 54.3, endSec: 58.0, text: '충분히 온톨로지로 활용을 할 수가 있어서 제가 이런 걸 하나 만들어 놨고요.' },
      ],
    },
  },
  // ─── Hook002 ───
  {
    id: 'Hook002',
    props: {
      audioFile: 'h002-audio.m4a',
      introVideo: 'h002-intro.mp4',
      outroVideo: 'h002-outro.mp4',
      introSec: 4,
      outroStartSec: 52,
      totalSec: 55,
      scenes: [
        { type: 'text' as const, startSec: 6.5, endSec: 12.9 },
        { type: 'text' as const, startSec: 12.9, endSec: 19.4 },
        { type: 'layers' as const, startSec: 19.4, endSec: 26.4 },
        { type: 'feedbackLoop' as const, startSec: 26.4, endSec: 32.9 },
        { type: 'feedbackLoop' as const, startSec: 32.9, endSec: 39.4 },
        { type: 'text' as const, startSec: 39.4, endSec: 44.9 },
        { type: 'feedbackLoop' as const, startSec: 44.9, endSec: 51.4 },
        { type: 'feedbackLoop' as const, startSec: 51.4, endSec: 54.8 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 6.5, text: '쓰면 쓸수록 똑똑해져야 되는데 맨날 리셋이 되면 그거는 저희가 AI랑 일하는 이유가 없죠. 숫자 틀리는 거 조심해' },
        { startSec: 6.5, endSec: 12.9, text: '숫자는 한 번 더 검증해 라던지 난 이거는 너의 의견에 동의하지 않아 별로야 구려' },
        { startSec: 12.9, endSec: 19.4, text: '이런 것들에 대한 거부 정보 이런 것들을 여러 가지로 저장을 해놓습니다. 그래서 한 번 뭐라 했는지' },
        { startSec: 19.4, endSec: 26.4, text: '두 번 뭐라 했는지 세 번 뭐라 했는지 이런 반영 임객 값에 대해서 얘가 요거를 좀 강력하게 반영하기도 하고 그냥 가볍게' },
        { startSec: 26.4, endSec: 32.9, text: '반영하기도 하고 이런 피드백 루프가 있어요. 그래서 에이전트 시스템을 구축하게 되면 이런 피드백 루프를' },
        { startSec: 32.9, endSec: 39.4, text: '잘 구축을 해놔야 사실 이득이 있는 거예요. 일하는 이유가 없죠. 맨날 다 알려줘야 되는데 그래서 RLVR 관점에서' },
        { startSec: 39.4, endSec: 44.9, text: '레인포스 러닝 버리파이어드 위얼드 그래서 검증 가능한' },
        { startSec: 44.9, endSec: 51.4, text: '뭔가 보상 시그널을 계속 줌으로써 날리지를 러닝하는 것이 레인포스 된다.' },
        { startSec: 51.4, endSec: 54.8, text: '학습되는 이런 루프를 만들어 놓는 것들이 굉장히 또' },
      ],
    },
  },
  // ─── Hook003 ───
  {
    id: 'Hook003',
    props: {
      audioFile: 'h003-audio.m4a',
      introVideo: 'h003-intro.mp4',
      outroVideo: 'h003-outro.mp4',
      introSec: 4,
      outroStartSec: 60,
      totalSec: 63,
      scenes: [
        { type: 'text' as const, startSec: 5.5, endSec: 10.7 },
        { type: 'text' as const, startSec: 10.7, endSec: 16.5 },
        { type: 'agenthub' as const, startSec: 16.5, endSec: 21.2 },
        { type: 'agenthub' as const, startSec: 21.2, endSec: 27.8 },
        { type: 'text' as const, startSec: 27.8, endSec: 32.4 },
        { type: 'text' as const, startSec: 32.4, endSec: 37.5 },
        { type: 'layers' as const, startSec: 37.5, endSec: 44.2 },
        { type: 'agenthub' as const, startSec: 44.2, endSec: 49.2 },
        { type: 'stats' as const, startSec: 49.2, endSec: 55.0 },
        { type: 'text' as const, startSec: 55.0, endSec: 58.0 },
        { type: 'layers' as const, startSec: 58.0, endSec: 63.0 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 5.5, text: 'CEO 스태프 에이전트 시스템이라고 부르기도 하고요. 그래서 말 그대로 CEO의 일을 전부 다 도와주는 시스템을 만들었어요. 사실 이 에이전트 시스템 사례가 엄청 스펙이 큽니다.' },
        { startSec: 5.5, endSec: 10.7, text: '스펙이 큰데 이 과정을 좀 다 설명드리는 게 좋을 것 같아서' },
        { startSec: 10.7, endSec: 16.5, text: '가지고 왔고 설명을 좀 드려볼게요. 정확히는 에이전트 팀을 구축을 했고요.' },
        { startSec: 16.5, endSec: 21.2, text: '그 업무에 필요한 에이전트 팀 그래서 CEO 스태프 팀이라고 부르면 됩니다.' },
        { startSec: 21.2, endSec: 27.8, text: 'CEO 스태프 에이전트 시스템이라고 부르기도 하고요. 그래서 여기 중에서도 콘텐츠, 저희가 전문의 콘텐츠니까' },
        { startSec: 27.8, endSec: 32.4, text: '콘텐츠 쪽에 피처가 굉장히 특화되어 있는 부분이 하나 있고요.' },
        { startSec: 32.4, endSec: 37.5, text: '그것과 별개로 그냥 CEO의 많은 일들을 도와줄 수 있는 것들이 될 것 같아서' },
        { startSec: 37.5, endSec: 44.2, text: '에이전트 팀과 이 에이전트 팀이 일하는 하네스를 설계하는 케이스를 좀 설명을 드려보려고 합니다.' },
        { startSec: 44.2, endSec: 49.2, text: '첫 번째로 이제 설명드릴 거는 CEO 스태프 에이전트 시스템에는' },
        { startSec: 49.2, endSec: 55.0, text: '18개의 에이전트가 있고요. 125개의 스킬을 익히고 있습니다.' },
        { startSec: 55.0, endSec: 58.0, text: '이거를 좀 차근차근 설명 드려볼게요.' },
        { startSec: 58.0, endSec: 63.0, text: '첫 번째로 이제 CEO 스태프는 5개의 레이어를 통해서 업무를 수행하게 되는데요.' },
      ],
    },
  },
  // ─── Hook004 ───
  {
    id: 'Hook004',
    props: {
      audioFile: 'h004-audio.m4a',
      introVideo: 'h004-intro.mp4',
      outroVideo: 'h004-outro.mp4',
      introSec: 4,
      outroStartSec: 54,
      totalSec: 57,
      scenes: [
        { type: 'text' as const, startSec: 7.2, endSec: 13.4 },
        { type: 'pipeline' as const, startSec: 13.4, endSec: 20.4 },
        { type: 'text' as const, startSec: 20.4, endSec: 25.7 },
        { type: 'text' as const, startSec: 25.7, endSec: 31.9 },
        { type: 'pipeline' as const, startSec: 31.9, endSec: 37.9 },
        { type: 'pipeline' as const, startSec: 37.9, endSec: 44.9 },
        { type: 'text' as const, startSec: 44.9, endSec: 50.5 },
        { type: 'pipeline' as const, startSec: 50.5, endSec: 57.4 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 7.0, text: '소재화할 수 있는 것들을 찾아요. 근데 요거 잘 생각해보면 컨텐츠 마케터가 회사에서 진짜 하는 일이에요. 실제로 하는 일을 모니터 에이전트가 대신한다.' },
        { startSec: 7.2, endSec: 13.4, text: '얘는 컨텐츠에 좀 특화되어 있는 애거든요. 그래서 컨텐츠를 어떻게 만드는가 를 좀 설명을 드릴게요.' },
        { startSec: 13.4, endSec: 20.4, text: '컨텐츠 마케팅 파이프라인 이라는 게 있고요. 첫 번째로 5개 정도의 파이프라인을 통해서 얘가 일을 합니다.' },
        { startSec: 20.4, endSec: 25.7, text: '첫 번째로는 슬랙이랑 노션이랑 그리고 외부의 동향을 파악을 해요.' },
        { startSec: 25.7, endSec: 31.9, text: '그래서 외부 동향이라고 한다면 경쟁사가 될 수도 있고 그냥 업계 뉴스, 링크 등이' },
        { startSec: 31.9, endSec: 37.9, text: '이런 것들을 포함을 해가지고 소재를 발굴하는 애가 있습니다. 얘가 모니터링 에이전트고요.' },
        { startSec: 37.9, endSec: 44.9, text: '모니터 에이전트가 지금 회사에서 돌아가는 여러 가지 것들 중에서 소재화할 수 있는 것들을 찾아요. 모니터 에이전트가 대신한다.' },
        { startSec: 44.9, endSec: 50.5, text: '근데 저희 사람이라면 슬랙의 모든 채널에 다 들어가 보지 않잖아요. 들어가 볼 수도 없고' },
        { startSec: 50.5, endSec: 57.4, text: '근데 그걸 모니터 에이전트는 슬랙이랑 노션의 변경 사항들을 다 모니터링하고 있습니다. 다만 요 부분은' },
        { startSec: 57.4, endSec: 64.0, text: '보안의 이슈가 하나 있어요. 그러니까 좀 예민한 채널이나 예민한 페이지는 공개하면 안 되잖아요. 그런 것들은' },
        { startSec: 64.0, endSec: 71.0, text: '잘 선택해서 하셔야 되고 요 케이스의 경우에는 합의된 채널과 합의된 지식들만 모니터링을 할 수 있게' },
        { startSec: 71.0, endSec: 77.4, text: '구축이 되어 있습니다. 그래서 모니터를 해서 아 지금 회사에 이런 일이 있고 바깥에 요 업계에서' },
        { startSec: 77.4, endSec: 83.5, text: '요런 게 이슈인데 이런 거를 소재로 뽑아보면 이런 게 나올 것 같아요. 라고 해서 드래프트 에이전트가' },
        { startSec: 83.5, endSec: 89.6, text: '소재를 주제를 뽑아요. 주제를 뽑고 내가 그 주제를 선택했잖아요. 몇 개를 뽑았으면 이거를' },
        { startSec: 89.6, endSec: 96.0, text: 'seo와 geo와 aeo에 최적화된 컨텐츠를 만들게 됩니다. 그 기본적으로 여기는' },
        { startSec: 96.0, endSec: 102.5, text: '롱폰 컨텐츠를 만들어가지고 블로그 초안이 나와요. 블로그 초안이 나오면 이걸 이제 휴먼아이저 에이전트를 써서' },
        { startSec: 102.5, endSec: 105.0, text: 'AI의 이런 물을 좀 빼는 작업을 하게 되고요.' },
      ],
    },
  },
  // ─── Process002 ───
  {
    id: 'Process002',
    props: {
      audioFile: 'p002-audio.m4a',
      introVideo: 'p002-intro.mp4',
      outroVideo: 'p002-outro.mp4',
      introSec: 4,
      outroStartSec: 84,
      totalSec: 87,
      scenes: [
        { type: 'comparison' as const, startSec: 6.0, endSec: 11.1 },
        { type: 'comparison' as const, startSec: 11.1, endSec: 17.7 },
        { type: 'ontologyGrid' as const, startSec: 17.7, endSec: 23.4 },
        { type: 'text' as const, startSec: 23.4, endSec: 29.0 },
        { type: 'text' as const, startSec: 29.0, endSec: 34.1 },
        { type: 'ontologyGrid' as const, startSec: 34.1, endSec: 39.3 },
        { type: 'ontologyGrid' as const, startSec: 39.3, endSec: 47.3 },
        { type: 'comparison' as const, startSec: 47.3, endSec: 53.0 },
        { type: 'text' as const, startSec: 53.0, endSec: 57.6 },
        { type: 'ontologyGrid' as const, startSec: 57.6, endSec: 62.3 },
        { type: 'ontologyGrid' as const, startSec: 62.3, endSec: 66.4 },
        { type: 'comparison' as const, startSec: 66.4, endSec: 71.0 },
        { type: 'ontologyGrid' as const, startSec: 71.0, endSec: 78.3 },
        { type: 'ontologyGrid' as const, startSec: 78.5, endSec: 83.5 },
        { type: 'text' as const, startSec: 83.5, endSec: 87.0 },
      ],
      subtitles: [
        { startSec: 0.0, endSec: 0.9, text: '그렇고요. 그래서 일단 기본적으로 날리지 베이스 온톨로지 구축부터 사실 시작을 했어요.' },
        { startSec: 0.9, endSec: 6.0, text: '왜냐하면 Gemini나 GPT나 이런 여러분들이 흔히' },
        { startSec: 6.0, endSec: 11.1, text: '사용하시는 프론티어어 LLM 모델도 일을 잘 하잖아요.' },
        { startSec: 11.1, endSec: 17.7, text: '근데 걔네랑 에이전트 팀의 차이가 뭐냐고 한다면 우리 회사의 맥락을 알고 있냐 아니냐 이 차이거든요.' },
        { startSec: 17.7, endSec: 23.4, text: '그런 의미에서 온톨로지는 우리 회사의 맥락을 신입사원 온보딩 교육하듯이 역사가 어떻게 되고' },
        { startSec: 23.4, endSec: 29.0, text: '연역이 어떻게 되고 매출 규모가 어떻게 되고 주요 제품이 뭐며 주요 기능이 뭐며' },
        { startSec: 29.0, endSec: 34.1, text: '이런 개요, 팀, 제품, 기술, 시장, 투자 상황, 로드맵,' },
        { startSec: 34.1, endSec: 39.3, text: '고객 이런 것들의 정보를 잘 정리해 놓은 게 온톨로지예요.' },
        { startSec: 39.3, endSec: 47.3, text: '이 온톨로지라는 것들이 원래는 되게 구축하기가 많이 어렵고 수작업도 굉장히 많이 들어가고 다양한 데이터가 필요했는데' },
        { startSec: 47.3, endSec: 53.0, text: 'AI를 활용하면 온톨로지 구축이 좀 간단한 거의 경우에는 비교적 쉽게 됩니다.' },
        { startSec: 53.0, endSec: 57.6, text: '비교적 쉽게 되고 예전처럼 아주 고급 기술이 아니라 지금은' },
        { startSec: 57.6, endSec: 62.3, text: '마크다운 기반으로 온톨로지로 사용할 만한 것들을 지식체계를 잘 정리해 놓으면' },
        { startSec: 62.3, endSec: 66.4, text: '충분히 온톨로지로 활용을 할 수가 있어서 제가 이런 걸 하나 만들어 놨고요.' },
        { startSec: 66.4, endSec: 71.0, text: '이런 거를 여러분들 많이 쓰신 옵시디언 같은 데다 연결하면' },
        { startSec: 71.0, endSec: 75.5, text: '지식 그래프로 관계를 맺은 지식 그래프로도 볼 수가 있어요.' },
        { startSec: 75.5, endSec: 78.3, text: '그래서 이렇게 온톨로지를 구축하는 일부터 했습니다.' },
        { startSec: 78.5, endSec: 87.0, text: '이걸 하면은 쉽게 말하면 진짜 AI가 우리 회사에서 제일 장기 근속한 사람처럼 여러 가지 속속들이 알게 되는 효과가 있어요.' },
      ],
    },
  },
  // ─── Process003 ───
  {
    id: 'Process003',
    props: {
      audioFile: 'p003-audio.m4a',
      introVideo: 'p003-intro.mp4',
      outroVideo: 'p003-outro.mp4',
      introSec: 4,
      outroStartSec: 64,
      totalSec: 67,
      scenes: [
        { type: 'text' as const, startSec: 7.0, endSec: 11.9 },
        { type: 'stats' as const, startSec: 11.9, endSec: 16.8 },
        { type: 'agenthub' as const, startSec: 16.8, endSec: 23.3 },
        { type: 'text' as const, startSec: 23.3, endSec: 28.0 },
        { type: 'agenthub' as const, startSec: 28.0, endSec: 34.9 },
        { type: 'agenthub' as const, startSec: 34.9, endSec: 39.9 },
        { type: 'text' as const, startSec: 39.9, endSec: 43.2 },
        { type: 'agenthub' as const, startSec: 43.2, endSec: 48.2 },
        { type: 'text' as const, startSec: 48.2, endSec: 51.9 },
        { type: 'agenthub' as const, startSec: 52.3, endSec: 57.3 },
        { type: 'text' as const, startSec: 57.3, endSec: 60.4 },
        { type: 'layers' as const, startSec: 60.4, endSec: 67.0 },
      ],
      subtitles: [
        { startSec: 0.3, endSec: 7.0, text: '16개를 만들었는데 운영을 하시다가 실제로 TalentOps라고 해가지고 이제 오퍼레이션 하는' },
        { startSec: 7.0, endSec: 11.9, text: '탤런트 오퍼레이션 하는 에이전트를 이제 사내에서 직접 추가하셔서' },
        { startSec: 11.9, endSec: 16.8, text: '총 17개 에이전트가 있고 나머지 1개 18개라고 제가 했잖아요.' },
        { startSec: 16.8, endSec: 23.3, text: '나머지 1개는 오케스트레이터예요. 오케스트레이터라는 건 에이전트 팀에서 좀 가장 중심이 되는 애인데' },
        { startSec: 23.3, endSec: 28.0, text: '오케스트라 할 때 이제 여러 가지 애들이 같이 일할 수 있도록 조종하는 애' },
        { startSec: 28.0, endSec: 34.9, text: '이렇게 협업을 할 수 있게끔 만드는 애가 있습니다. 그래서 CEO 스태프라는 오케스트레이터가 있고요.' },
        { startSec: 34.9, endSec: 43.2, text: '그 아래에 프로덕트, 마케팅, 파이낸스, 데이터, 세일즈, 리걸, 리서치, HR 뭐 이런 애들이 아래에 있는 거예요.' },
        { startSec: 43.2, endSec: 51.9, text: '그래서 처음에 업무를 하다를 받는 애는 이걸 쓰는 사람, CEO가 업무를 하다라는 건 CEO 스태프한테 하다를 하게 되고요.' },
        { startSec: 52.3, endSec: 60.4, text: 'CEO 스태프가 여러 에이전트들한테 이걸 뿌려가지고 일을 시키게 되는 그래서 에이전트 허브 시스템이 하나 생기게 됩니다.' },
        { startSec: 60.4, endSec: 67.0, text: '그리고 이제 CEO 스태프는 되게 다양한 스킬들을 참조하게 되고요. 이거는 그냥 넘어가도 될 것 같아요.' },
      ],
    },
  },
  // ─── Process004 ───
  {
    id: 'Process004',
    props: {
      audioFile: 'p004-audio.m4a',
      introVideo: 'p004-intro.mp4',
      outroVideo: 'p004-outro.mp4',
      introSec: 4,
      outroStartSec: 102,
      totalSec: 105,
      scenes: [
        { type: 'pipeline' as const, startSec: 6.4, endSec: 13.4 },
        { type: 'text' as const, startSec: 13.4, endSec: 18.7 },
        { type: 'text' as const, startSec: 18.7, endSec: 24.9 },
        { type: 'pipeline' as const, startSec: 24.9, endSec: 30.9 },
        { type: 'pipeline' as const, startSec: 30.9, endSec: 37.5 },
        { type: 'text' as const, startSec: 37.5, endSec: 43.3 },
        { type: 'pipeline' as const, startSec: 43.3, endSec: 49.3 },
        { type: 'pipeline' as const, startSec: 49.3, endSec: 55.8 },
        { type: 'text' as const, startSec: 55.8, endSec: 61.1 },
        { type: 'text' as const, startSec: 61.1, endSec: 67.6 },
        { type: 'pipeline' as const, startSec: 67.6, endSec: 73.8 },
        { type: 'text' as const, startSec: 73.8, endSec: 80.1 },
        { type: 'pipeline' as const, startSec: 80.1, endSec: 86.7 },
        { type: 'pipeline' as const, startSec: 86.7, endSec: 92.8 },
        { type: 'comparison' as const, startSec: 92.8, endSec: 99.0 },
        { type: 'pipeline' as const, startSec: 99.0, endSec: 105.0 },
      ],
      subtitles: [
        { startSec: 0.2, endSec: 6.4, text: '얘는 컨텐츠에 좀 특화되어 있는 애거든요. 그래서 컨텐츠를 어떻게 만드는가 를 좀 설명을 드릴게요.' },
        { startSec: 6.4, endSec: 13.4, text: '컨텐츠 마케팅 파이프라인 이라는 게 있고요. 첫 번째로 5개 정도의 파이프라인을 통해서 얘가 일을 합니다.' },
        { startSec: 13.4, endSec: 18.7, text: '첫 번째로는 슬랙이랑 노션이랑 그리고 외부의 동향을 파악을 해요.' },
        { startSec: 18.7, endSec: 24.9, text: '그래서 외부 동향이라고 한다면 경쟁사가 될 수도 있고 그냥 업계 뉴스, 링크 등이' },
        { startSec: 24.9, endSec: 30.9, text: '이런 것들을 포함을 해가지고 소재를 발굴하는 애가 있습니다. 얘가 모니터링 에이전트고요.' },
        { startSec: 30.9, endSec: 37.5, text: '모니터 에이전트가 지금 회사에서 돌아가는 여러 가지 것들 중에서 소재화할 수 있는 것들을 찾아요.' },
        { startSec: 37.5, endSec: 43.3, text: '근데 요거 잘 생각해보면 컨텐츠 마케터가 회사에서 진짜 하는 일이에요. 실제로 하는 일을' },
        { startSec: 43.3, endSec: 49.3, text: '모니터 에이전트가 대신한다. 근데 저희 사람이라면 슬랙의 모든 채널에 다 들어가 보지 않잖아요.' },
        { startSec: 49.3, endSec: 55.8, text: '들어가 볼 수도 없고 근데 그걸 모니터 에이전트는 슬랙이랑 노션의 변경 사항들을 다 모니터링하고 있습니다.' },
        { startSec: 55.8, endSec: 61.1, text: '다만 요 부분은 보안의 이슈가 하나 있어요. 그러니까 좀 예민한 채널이나' },
        { startSec: 61.1, endSec: 67.6, text: '예민한 페이지는 공개하면 안 되잖아요. 그런 것들은 잘 선택해서 하셔야 되고 요 케이스의 경우에는' },
        { startSec: 67.6, endSec: 73.8, text: '합의된 채널과 합의된 지식들만 모니터링을 할 수 있게 구축이 되어 있습니다. 그래서 모니터를 해서' },
        { startSec: 73.8, endSec: 80.1, text: '아 지금 회사에 이런 일이 있고 바깥에 요 업계에서 요런 게 이슈인데 이런 거를 소재로 뽑아보면' },
        { startSec: 80.1, endSec: 86.7, text: '이런 게 나올 것 같아요. 라고 해서 드래프트 에이전트가 소재를 주제를 뽑아요. 주제를 뽑고' },
        { startSec: 86.7, endSec: 92.8, text: '내가 그 주제를 선택했잖아요. 몇 개를 뽑았으면 이거를 seo와 geo와 aeo에 최적화된' },
        { startSec: 92.8, endSec: 99.0, text: '컨텐츠를 만들게 됩니다. 그 기본적으로 여기는 롱폰 컨텐츠를 만들어가지고 블로그 초안이 나와요.' },
        { startSec: 99.0, endSec: 105.0, text: '블로그 초안이 나오면 이걸 이제 휴먼아이저 에이전트를 써서 AI의 이런 물을 좀 빼는 작업을 하게 되고요.' },
      ],
    },
  },
]